// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package v2

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Result defines model for Result.
type Result struct {
	AnimeName  *string `json:"anime_name,omitempty"`
	ArtistHref *string `json:"artist_href,omitempty"`
	ArtistName *string `json:"artist_name,omitempty"`
	SourceUrl  *string `json:"source_url,omitempty"`
	Url        string  `json:"url"`
}

// SearchParams defines parameters for Search.
type SearchParams struct {
	Query    string  `form:"query" json:"query"`
	Type     int     `form:"type" json:"type"`
	Category *string `form:"category,omitempty" json:"category,omitempty"`
	Amount   *int    `form:"amount,omitempty" json:"amount,omitempty"`
}

// GetCategoryFilesParams defines parameters for GetCategoryFiles.
type GetCategoryFilesParams struct {
	Amount *int `form:"amount,omitempty" json:"amount,omitempty"`
}
